### ISSUE TITLE
Add in google analytics

### ISSUE THREAD

**Issue by adamrobinson361** [dfe-analytical-services/exclusion-statistics#3]
## Background

As discussed look into adding google analytics into the app for basic usage. Also decide if you want to track individual events

**Comment by TomFranklin** [comment]
New R package has been developed that could help with this - I like the live number of people looking at the app element! https://www.r-bloggers.com/log-shiny-app-visitors-and-r-usage-to-google-analytics/ taken from https://github.com/bnosac/GAlogger

**Comment by TomFranklin** [comment]
google analytics added.
